import { PolicyPage } from "../components/PolicyPage";

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Your information" title="Privacy Policy" intro="This policy explains how Kashung Enterprise handles personal information when you visit our website, contact us, or work with us on a website, software, or app project." sections={[
    { title: "Information we collect", points: ["Contact details such as your name, email address, phone number, organisation, and social-media handle.", "Project information, briefs, messages, files, feedback, credentials or access details you choose to provide.", "Commercial and transaction records such as proposals, invoices, payment status, and tax information. We do not intentionally store full payment-card details.", "Basic technical information such as device, browser, IP address, referral page, and site-usage data when hosting, security, or analytics tools collect it."] },
    { title: "How we use information", points: ["Respond to enquiries and assess project requirements.", "Prepare proposals, deliver services, communicate progress, process payments, and provide support.", "Secure, maintain, analyse, and improve our website and services.", "Keep business, tax, contractual, and compliance records.", "Send marketing only where you have requested it or where otherwise permitted, with an option to stop."] },
    { title: "Consent and lawful use", paragraphs: ["We process information for the purpose explained when it is collected, to perform or prepare a contract with you, to comply with law, for legitimate business and security needs, or with your consent where required. Where processing relies on consent, you may withdraw it by contacting us; withdrawal does not affect processing already lawfully completed."] },
    { title: "Sharing and service providers", paragraphs: ["We do not sell or rent personal information. We may share only what is necessary with trusted hosting, cloud, email, analytics, collaboration, payment, accounting, legal, or development providers; project collaborators bound by appropriate duties; authorities when legally required; or a successor in a genuine business transfer."], points: ["A client is responsible for the privacy compliance of user data collected through the client’s own delivered product unless a separate data-processing agreement assigns responsibilities differently.", "Where a project requires us to handle end-user data for a client, we act only within the agreed instructions and scope."] },
    { title: "Cookies and analytics", paragraphs: ["Our site or hosting provider may use essential technologies for security, performance, and basic operation. If optional analytics or marketing cookies are introduced, we will provide appropriate notice or choices where required. You may control cookies through your browser, although blocking essential technologies can affect functionality."] },
    { title: "Retention", paragraphs: ["We keep information only as long as reasonably needed for the stated purpose, project support, dispute handling, security, backups, or legal, accounting, and tax duties. Retention periods vary by record. When information is no longer required, we delete, anonymise, or securely isolate it where practicable."] },
    { title: "Security", paragraphs: ["We use reasonable organisational and technical safeguards appropriate to the information and our business. No internet transmission or storage method is completely secure. Clients should avoid sending production passwords in ordinary email where a safer transfer method is available and should rotate shared credentials after handover."] },
    { title: "Your choices and rights", paragraphs: ["Subject to applicable law, you may ask what personal information we hold about you, request correction or deletion, withdraw consent, raise a grievance, or ask about our handling practices. We may need to verify identity and may retain information where law or a valid legal need requires it."], points: ["Send requests to kashthot@gmail.com with enough detail for us to identify the relevant records.", "You may nominate another individual to exercise applicable data rights in circumstances recognised by law.", "You may complain to the competent authority where that right applies."] },
    { title: "Children", paragraphs: ["Our services are intended for businesses, startups, entrepreneurs, and adults. We do not knowingly seek personal information from children. If you believe a child has provided information without appropriate authorisation, contact us so we can review and remove it where required."] },
    { title: "International processing", paragraphs: ["Some technology providers may process information outside your state or country. Where this occurs, we select reputable providers and use safeguards reasonably appropriate to the service and applicable law."] },
    { title: "Updates and contact", paragraphs: ["We may revise this policy when our practices or legal obligations change. The effective date above identifies the current version. Questions, requests, or grievances may be sent to Kashung Enterprise at kashthot@gmail.com. We will review and respond within a reasonable period."] }
  ]} />;
}
