import { PolicyPage } from "../components/PolicyPage";

export default function TermsPage() {
  return <PolicyPage eyebrow="Service agreement" title="Terms of Service" intro="These terms explain how we scope, build, deliver, and support digital projects. A signed proposal, quotation, statement of work, invoice, or written acceptance may add project-specific terms; if they conflict, the project-specific written agreement controls." updatedAt="29 August 2026" sections={[
    { title: "About these terms", paragraphs: ["These Terms apply when a client engages Kashung Enterprise (“we”, “us”, or “our”) for website, software, application, design, consulting, maintenance, or related digital services. By approving a proposal, paying an invoice, or asking us to begin work, the client agrees to these Terms."] },
    { title: "Scope and approval", paragraphs: ["The deliverables, features, timeline, price, and assumptions will be recorded in a proposal, quotation, message, or statement of work. Work outside the agreed scope is a change request and may require a revised price and schedule."], points: ["The client must review the scope and final project price before work begins.", "Approvals and instructions sent by the client’s authorised contact may be relied upon.", "Material changes requested after approval may pause the timeline until cost and timing are agreed."] },
    { title: "Payment terms", paragraphs: ["Payment is split into two compulsory milestones unless a written project agreement says otherwise. Prices are stated in Indian Rupees unless another currency is agreed; applicable taxes and third-party charges will be identified separately where relevant."], points: ["A compulsory 50% upfront payment is due after the project scope and final price have been discussed and approved.", "We begin and reserve production time only after the upfront payment clears; once work starts, the upfront payment is non-refundable.", "The remaining 50% is due at final deployment after the client review and included revision stage.", "Final handover, source files, credentials, ownership transfer, or continued production access may be withheld until all invoices are paid."] },
    { title: "Review and final deployment", paragraphs: ["“Review deployment” means the agreed deliverable has been placed on a live, staging, test, or review environment and is reasonably available for the client to inspect. It does not mean every optional enhancement or future change has been completed.", "After eligible review feedback has been addressed, we proceed to final deployment. At final deployment, the compulsory remaining 50% becomes due in full."] },
    { title: "Included revision period", paragraphs: ["The client receives 7 calendar days beginning when the review deployment is shared to submit reasonable in-scope requests in writing. Sending clear, consolidated feedback helps us complete them efficiently."], points: ["Included revisions cover reasonable adjustments within the originally approved scope.", "New features, redesigned flows, changed business requirements, additional pages, integrations, or content entry beyond scope are separately chargeable.", "Unused revision time does not roll over. Future edits, revisions, or changes requested after the 7-day period are quoted as additional work.", "Fixes for a reproducible defect that makes an agreed feature materially fail are distinguished from new revisions and will be assessed reasonably."] },
    { title: "Client responsibilities", points: ["Provide accurate content, brand assets, feedback, approvals, account access, and legal notices on time.", "Confirm that supplied materials may lawfully be used and do not infringe third-party rights.", "Review deployments promptly and maintain backups of content and credentials delivered to the client.", "Pay third-party costs such as domains, hosting, app-store fees, licences, APIs, SMS, email, or cloud services unless expressly included."] },
    { title: "Timelines and delays", paragraphs: ["Delivery estimates depend on timely feedback, access, content, and third-party services. Client delays, scope changes, force majeure events, platform reviews, or external provider failures may extend the schedule. We will communicate material changes reasonably."] },
    { title: "Intellectual property", paragraphs: ["After full payment, the client receives ownership of the custom final deliverables created specifically for the project, except for our pre-existing tools, reusable code, know-how, templates, licensed assets, open-source software, and third-party components. Those items remain subject to their applicable licences.", "Until full payment, all deliverables remain our property and any access is for review only. Unless confidentiality is agreed in writing, we may identify the client and display non-confidential completed work in our portfolio and marketing."] },
    { title: "Third-party services", paragraphs: ["Projects may rely on hosting providers, app stores, payment gateways, APIs, libraries, plugins, fonts, or other third parties. Their terms, pricing, availability, security, and policy decisions are outside our control. We are not responsible for interruptions or changes caused by them, but we will reasonably assist with issues within our agreed scope."] },
    { title: "Warranties and liability", paragraphs: ["We will perform services with reasonable skill and care. Except for rights that cannot legally be excluded, deliverables are provided without a guarantee of uninterrupted operation, specific revenue, search ranking, user growth, funding, or compatibility with future third-party changes.", "To the extent permitted by law, neither party is liable for indirect, incidental, special, or consequential loss. Our aggregate liability arising from a project will not exceed the fees actually paid to us for that project. Nothing in these Terms limits liability that cannot lawfully be limited."] },
    { title: "Suspension and termination", paragraphs: ["We may pause work or access for overdue payment, missing dependencies, unlawful use, abuse, or a material breach. Either party may terminate for a material breach not remedied within a reasonable written notice period. Fees for completed work, reserved production time, committed third-party costs, and achieved milestones remain payable. Refunds are governed by our Refund Policy."] },
    { title: "Governing law and contact", paragraphs: ["These Terms are governed by the laws of India. Subject to applicable consumer rights and mandatory law, courts with jurisdiction in Manipur, India will have jurisdiction over disputes. The parties should first attempt to resolve concerns in good faith by writing to kashthot@gmail.com."] }
  ]} />;
}
