import { PolicyPage } from "../components/PolicyPage";

export default function RefundPolicyPage() {
  return <PolicyPage eyebrow="Payments & revisions" title="Refund Policy" intro="Our work is custom, time-reserved, and built to an approved scope. This policy explains the payment milestones, when fees become earned, and how the free revision period works." sections={[
    { title: "Payment schedule", points: ["50% upfront is payable only after the project scope and final price have been discussed and approved.", "The upfront payment confirms the engagement, reserves production capacity, and authorises us to begin.", "The remaining 50% is compulsory and becomes due upon initial deployment of the agreed project."] },
    { title: "No refund after advance payment", paragraphs: ["Once the 50% upfront payment has been made and the engagement is confirmed, it is non-refundable. This applies because we reserve time, begin planning and production, and may incur project costs immediately.", "If the client pauses, cancels, changes direction, fails to provide required materials, or chooses not to continue after work has begun, the upfront payment will not be returned. This rule is subject to any remedy or refund that cannot be excluded under applicable law."] },
    { title: "Final payment after deployment", paragraphs: ["Initial deployment occurs when the agreed deliverable is made available on a live, staging, test, or review environment for inspection. At that milestone, the remaining 50% is due in full.", "Revision requests, minor defects, delayed client content, or a decision not to launch publicly do not cancel or postpone the final payment where the agreed project has been initially deployed. Final files, ownership transfer, credentials, and continued production access may be withheld until payment clears."] },
    { title: "Free 15-day revision period", paragraphs: ["A free revision period runs for 15 calendar days from initial deployment. The client should review the project and submit one clear, consolidated list of requested adjustments during this period."], points: ["Covered: reasonable corrections and adjustments within the approved scope.", "Not covered: new features, new pages, major redesigns, changed requirements, extra integrations, or work that was not originally agreed.", "Out-of-scope work and requests made after 15 days will be estimated and billed separately.", "The revision window is a service benefit and does not extend or defer the final-payment due date."] },
    { title: "Exceptions and service concerns", paragraphs: ["We do not promise discretionary refunds for change of mind, project cancellation, unused revision time, or delays caused by the client or third parties. If you believe we have materially failed to provide the agreed service, notify us promptly with details and allow a reasonable opportunity to investigate and correct the issue.", "Nothing in this policy removes rights or remedies that cannot be waived under applicable Indian law. Any legally required remedy will be assessed against the approved scope, work completed, amounts paid, and the circumstances of the project."] },
    { title: "Chargebacks and disputes", paragraphs: ["Before initiating a payment dispute or chargeback, contact us at kashthot@gmail.com so we can review the project record and attempt a good-faith resolution. An improper chargeback does not cancel amounts validly due under the agreement and may result in work, hosting, access, or handover being paused where lawful."] },
    { title: "Contact", paragraphs: ["For payment, cancellation, revision, or service concerns, email kashthot@gmail.com and include your name, project, invoice reference, and a clear explanation. We will respond within a reasonable period."] }
  ]} />;
}
