import { PolicyPage } from "../components/PolicyPage";

export default function RefundPolicyPage() {
  return <PolicyPage eyebrow="Payments & revisions" title="Refund Policy" intro="Our work is custom, time-reserved, and built to an approved scope. This policy explains the compulsory payment milestones, when fees become earned, and how the included revision period works." updatedAt="29 August 2026" sections={[
    { title: "Payment schedule", points: ["A compulsory 50% upfront payment is due after the project scope and final price have been discussed and approved.", "The upfront payment confirms the engagement, reserves production capacity, and authorises us to begin.", "The remaining 50% is compulsory and due at final deployment after the client review and included revision stage.", "Prices are in Indian Rupees unless otherwise agreed; applicable taxes and separately approved third-party charges may be added where relevant."] },
    { title: "No refund after work begins", paragraphs: ["Once the project has started, the 50% upfront payment is non-refundable. This applies because we reserve time, begin planning and production, and may incur project costs immediately.", "If the client pauses, cancels, changes direction, fails to provide required materials, or chooses not to continue after work has begun, the upfront payment will not be returned. This rule is subject to any remedy or refund that cannot be excluded under applicable law."] },
    { title: "Final payment after review", paragraphs: ["A review deployment occurs when the agreed deliverable is made available on a live, staging, test, or review environment for the client to inspect. We will address eligible feedback submitted during the included revision period before final deployment.", "At final deployment, the remaining 50% is due in full. Delayed client content, a decision not to launch publicly, or feedback outside the approved scope does not cancel the final-payment obligation. Final files, ownership transfer, credentials, and continued production access may be withheld until payment clears."] },
    { title: "Included revision period", paragraphs: ["The client receives 7 calendar days to review the project and submit reasonable in-scope adjustments in writing. The period begins when the review deployment is shared. Clear, consolidated feedback is encouraged so revisions can be completed efficiently."], points: ["Covered: reasonable corrections and adjustments within the approved scope.", "Not covered: new features, new pages, major redesigns, changed requirements, extra integrations, or work that was not originally agreed.", "Future edits, revisions, or change requests received after the 7-day period are chargeable and will be estimated separately.", "If no feedback is received during the review period, the approved work may proceed to final deployment and final invoicing."] },
    { title: "Exceptions and service concerns", paragraphs: ["We do not promise discretionary refunds for change of mind, project cancellation, unused revision time, or delays caused by the client or third parties. If you believe we have materially failed to provide the agreed service, notify us promptly with details and allow a reasonable opportunity to investigate and correct the issue.", "Nothing in this policy removes rights or remedies that cannot be waived under applicable Indian law. Any legally required remedy will be assessed against the approved scope, work completed, amounts paid, and the circumstances of the project."] },
    { title: "Chargebacks and disputes", paragraphs: ["Before initiating a payment dispute or chargeback, contact us at kashthot@gmail.com so we can review the project record and attempt a good-faith resolution. An improper chargeback does not cancel amounts validly due under the agreement and may result in work, hosting, access, or handover being paused where lawful."] },
    { title: "Contact", paragraphs: ["For payment, cancellation, revision, or service concerns, email kashthot@gmail.com and include your name, project, invoice reference, and a clear explanation. We will respond within a reasonable period."] }
  ]} />;
}
